"""M3 type-scale roles.

The figures come from Google's autogenerated token source (material-web,
Material 3 version 34.0.21), not from the spec page -- which serves a
JavaScript shell with no extractable table, and is why the copy in
`M3-References` is empty.

The tests below pin the sourcing as much as the behaviour: the scale must agree
with the four values the reference library corroborates independently, and must
settle the one it contradicts itself on.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from pycopper.spec import SpecError, parse_view
from pycopper.spec.loader import load_view
from pycopper.spec.models import TYPE_ROLES
from pycopper.spec.typescale import TYPE_SCALE


def view(scale: dict | None, style: dict):
    payload: dict = {"root": {"name": "t", "widget": "Text", "text": "x", "style": style}}
    if scale is not None:
        payload["type_scale"] = scale
    return parse_view(payload)


# ------------------------------------------------------------ vocabulary


def test_there_are_fifteen_roles() -> None:
    """M3: "15 baseline" styles, "from Display Large to Label Small"."""
    assert len(TYPE_ROLES) == 15
    assert TYPE_ROLES[0] == "display-large"
    assert TYPE_ROLES[-1] == "label-small"


def test_every_group_has_three_steps() -> None:
    for group in ("display", "headline", "title", "body", "label"):
        steps = [r for r in TYPE_ROLES if r.startswith(f"{group}-")]
        assert len(steps) == 3, group


def test_a_name_outside_the_vocabulary_is_rejected() -> None:
    with pytest.raises(SpecError):
        view({"title-large": 22}, {"text_style": "title-enormous"})


# ------------------------------------------------------------ resolution


def test_a_role_resolves_to_a_font_size() -> None:
    parsed = view({"title-large": 22}, {"text_style": "title-large"})
    assert parsed.root.style.font_size == 22.0


def test_resolution_happens_at_load() -> None:
    """So every widget downstream keeps reading a plain float, and a role
    costs nothing per frame."""
    parsed = view({"body-medium": 14}, {"text_style": "body-medium"})
    assert isinstance(parsed.root.style.font_size, float)


def test_a_role_beats_an_explicit_size() -> None:
    """Naming a role is the more specific statement of intent."""
    parsed = view({"title-large": 22}, {"text_style": "title-large", "font_size": 99})
    assert parsed.root.style.font_size == 22.0


def test_text_without_a_role_is_untouched() -> None:
    parsed = view({"title-large": 22}, {"font_size": 17})
    assert parsed.root.style.font_size == 17.0
    assert parsed.root.style.text_style is None


def test_roles_resolve_inside_nested_nodes_and_overlays() -> None:
    parsed = parse_view(
        {
            "type_scale": {"title-large": 22},
            "root": {
                "name": "root",
                "widget": "Column",
                "children": [
                    {"name": "deep", "widget": "Text", "style": {"text_style": "title-large"}}
                ],
            },
            "overlays": [
                {
                    "name": "d",
                    "widget": "Dialog",
                    "open": "true",
                    "style": {"text_style": "title-large"},
                }
            ],
        }
    )
    assert parsed.root.children[0].style.font_size == 22.0
    assert parsed.overlays[0].style.font_size == 22.0


def test_a_view_with_no_roles_is_not_rewritten() -> None:
    """The common case must not pay for a tree copy."""
    from pycopper.spec.typescale import apply_type_scale

    parsed = parse_view({"name": "t", "widget": "Text", "text": "x"})
    assert apply_type_scale(parsed) is parsed


# --------------------------------------------------------- missing sizes


def test_every_role_resolves_without_a_declared_scale() -> None:
    """The built-in scale covers all fifteen, so a view need declare nothing."""
    for role in TYPE_ROLES:
        parsed = view(None, {"text_style": role})
        assert parsed.root.style.font_size > 0


def test_a_view_overrides_the_built_in_scale_per_role() -> None:
    parsed = parse_view(
        {
            "type_scale": {"title-large": 30},
            "root": {
                "name": "root",
                "widget": "Column",
                "children": [
                    {"name": "a", "widget": "Text", "style": {"text_style": "title-large"}},
                    {"name": "b", "widget": "Text", "style": {"text_style": "body-medium"}},
                ],
            },
        }
    )
    assert parsed.root.children[0].style.font_size == 30.0
    assert parsed.root.children[1].style.font_size == TYPE_SCALE["body-medium"].size


# ---------------------------------------------------------------- sharing


def test_a_scale_can_live_in_its_own_file(tmp_path: Path) -> None:
    (tmp_path / "scale.yaml").write_text("title-large: 22\nbody-medium: 14\n")
    (tmp_path / "app.yaml").write_text(
        "type_scale: {source: scale.yaml}\n"
        "root: {name: t, widget: Text, text: x, style: {text_style: title-large}}\n"
    )
    parsed = load_view(tmp_path / "app.yaml")
    assert parsed.root.style.font_size == 22.0


def test_an_included_scale_is_watched_for_reload(tmp_path: Path) -> None:
    (tmp_path / "scale.yaml").write_text("title-large: 22\n")
    (tmp_path / "app.yaml").write_text(
        "type_scale: {source: scale.yaml}\n"
        "root: {name: t, widget: Text, text: x, style: {text_style: title-large}}\n"
    )
    sources: set[Path] = set()
    load_view(tmp_path / "app.yaml", sources=sources)
    assert {p.name for p in sources} == {"app.yaml", "scale.yaml"}


def test_a_scale_file_of_non_numbers_is_rejected(tmp_path: Path) -> None:
    (tmp_path / "scale.yaml").write_text("title-large: enormous\n")
    (tmp_path / "app.yaml").write_text(
        "type_scale: {source: scale.yaml}\nroot: {name: t, widget: Text, text: x}\n"
    )
    with pytest.raises(SpecError, match="maps each role to a number"):
        load_view(tmp_path / "app.yaml")


# ------------------------------------------------------------- provenance


def test_the_scale_has_all_fifteen_roles() -> None:
    assert set(TYPE_SCALE) == set(TYPE_ROLES)


def test_it_agrees_with_every_value_the_reference_library_corroborates() -> None:
    """Four roles appear with a size in `M3-References` independently of the
    token source. If those ever disagree, one of the two is wrong and this
    should say so loudly rather than let it pass."""
    corroborated = {
        "headline-medium": 28.0,  # app bar, expanded medium
        "title-large": 22.0,  # app bar title, small/centre-aligned
        "title-small": 14.0,
        "label-medium": 12.0,
    }
    for role, size in corroborated.items():
        assert TYPE_SCALE[role].size == size, role


def test_it_settles_the_contradiction_in_the_reference_library() -> None:
    """`headline-large` appears in `M3-References` as both 32sp and 36sp, in
    the same file. The token source says 32."""
    assert TYPE_SCALE["headline-large"].size == 32.0


def test_the_scale_descends_within_each_group() -> None:
    for group in ("display", "headline", "title", "body", "label"):
        sizes = [TYPE_SCALE[f"{group}-{s}"].size for s in ("large", "medium", "small")]
        assert sizes == sorted(sizes, reverse=True), group


def test_the_recorded_tokens_are_plausible() -> None:
    """Line height is never smaller than the size it belongs to, and weights
    are real Roboto weights -- a guard against a transcription slip."""
    for role, style in TYPE_SCALE.items():
        assert style.line_height >= style.size, role
        assert style.weight in (400, 500), role


def test_the_example_documents_its_provenance() -> None:
    """`examples/typescale.yaml` is now an override sample, but it must keep
    saying where the built-in figures came from."""
    path = Path(__file__).resolve().parents[1] / "examples/typescale.yaml"
    text = path.read_text()
    assert "material-web" in text
    assert "34.0.21" in text
